# required for supressing warnings of Tensorflow
import os
import warnings

# Suppress TensorFlow warnings
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'  # suppress info, warnings but lets out errors
warnings.filterwarnings("ignore", category=UserWarning, module='tensorflow')

# importing the actual libraries
import tensorflow as tf
from tensorflow import keras

# you need to fillin this yourself
# you choose the name of the best model generated when you run train.py
# for me the name is 'xception_v_script_17_0.956.h5'
# but for you it might be different name. So please change this variable with you model name
model_name = 'xception_v_script_17_0.956.h5'

#load the best model generated by the script
model = keras.models.load_model(model_name)

#convert to TF-Lite
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

# save the converted model to a file
with open('final_deployable_model.tflite', 'wb') as f_out:
    f_out.write(tflite_model)
    print('keras model successsfully converted to tflite')
f_out.close()
