# [api] 
# key = "haha-i-will-not-tell-you-this!"    # Placeholder for GitHub repo; actual key is stored in Streamlit Cloud secrets.

# If you push this file with key head -->> [api] and key value --> key = .., it would conflit and override the secrets/keys you have set in the
# Secrets section of the Settings in the Streamlit Cloud for your app. This is only for local development, I guess!

